### ISSUE TITLE
Use Fish Shell.

### ISSUE THREAD

**Issue by Uniminin** [ritiek/dotfiles#2]
Instead of zsh and powerline-shell use fish shell. It's way better.
https://fishshell.com
https://github.com/oh-my-fish/oh-my-fish
https://github.com/jorgebucaran/awesome-fish

**Comment by ritiek** [comment]
I did consider fish at first but it seems like it isn't backwards compatible with bash. So, I thought about avoiding fish since I wouldn't wanted to get in a habit of writing fish-only stuff that would break on bash (that would be bad since bash is the default shell for most distros).
